version: "3.8"

services:
  frontend:
    image: ghcr.io/sainiaditya1/sample-fullstack-application/frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: ghcr.io/sainiaditya1/sample-fullstack-application/backend:latest
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://postgres:password@database:5432/mydatabase"
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - database
      - redis

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  db-data:
